### PR TITLE
retire EntityStatement, use Note object and related_notes slot instead

### PR DESCRIPTION
**Pull request by gildossantos**
These changes affect the expression model. The expression working group will, at some point, need to specify new controlled vocabulary terms for all of the desired note types for expression data.

### CODE REVIEW

**Comment by draciti** [comment]
@gildossantos , duly noted. I added the issue to the EWG agenda. We are not meeting  over the summer. I will schedule a meeting in ~August to discuss. If you need this earlier let me know. thx

**Comment by sierra-moxon** [comment]
@draciti - do you think this PR can be merged before the fall?  We could merge it now, and then make further changes upon review by the WG in September?

**Comment by draciti** [comment]
@sierra-moxon fine with  me to merge now and make further changes upon review. Whichever works best for you. thanks!

**Comment by sierra-moxon** [comment]
I fixed the conflicts here by basically accepting @gildossantos changes over those in main.  @edwong57 - I merged your refactoring branch several weeks back.  Just adding a note here that we might want to do a quick pass through the expression.yaml to make sure I resolved conflicts to the latest advice from the expression WG.

**Pull request merged**
