### PR TITLE
update reference to conform to literature database

### PR DESCRIPTION
**Pull request by dougli1sqrd**
New PR into the correct repo! For https://agr-jira.atlassian.net/browse/SCRUM-1142

### CODE REVIEW

**Review by azurebrd — COMMENTED** [review]
date_last_modified_in_PubMed will eventually become date_last_modified_in_pubmed when we can change the database and API / data.  Right now our database calls it date_last_modified , which is not right.

**Comment by dougli1sqrd** [comment]
@azurebrd are you saying there should be a slot `date_last_modified_in_pubmed` still?

**Review by gildossantos — APPROVED** [review]

**Comment by azurebrd** [comment]
@dougli1sqrd There will eventually need to be a change from date_last_modified to date_last_modified_in_pubmed once the database and API change to match.  So, more of a heads up that it will change, but it hasn't yet.

**Comment by gildossantos** [comment]
@azurebrd - I added a few notes in the LinkML that explains how currently the `date_last_modified` should be renamed to `date_last_modified_in_pubmed`.

**Comment by azurebrd** [comment]
@gildossantos I see it, thanks Gil !

**Pull request merged**
