### PR TITLE
Add 'disease_annotation_curie' to DiseaseAnnotation class

### PR DESCRIPTION
**Pull request by chris-grove**
-replaced 'alliance_curie' in DiseaseAnnotation class with 'disease_annotation_curie' slot
- added slot definition for 'disease_annotation_curie'
- alphabetized slot definitions in phenotypeAndDiseaseAnnotation.yaml
- removed comment TO DO item for GOTerm

### CODE REVIEW

**Comment by chris-grove** [comment]
I will add test data

**Comment by chris-grove** [comment]
Test data added. I'm attempting to run 'make test' and 'make all'. Looks like I need to (re?)install XCode developer tools for Mac

**Comment by chris-grove** [comment]
'make test' is still giving me the same errors it has been:
`% make test
rm -rf target/*
rm -rf jsonschema/*
mkdir -p target/jsonschema
poetry run gen-json-schema  --closed -t ingest model/schema/allianceModel.yaml > target/jsonschema/allianceModel.schema.json
cp -pr target/jsonschema .
poetry run jsonschema -i test/data/allele_test.json jsonschema/allianceModel.schema.json
The currently activated Python version 3.7.4 is not supported by the project (^3.8).
Trying to find and use a compatible version. 
Using python3.8 (3.8.3)
Failed to parse 'jsonschema/allianceModel.schema.json': Expecting value: line 1 column 1 (char 0)
make: *** [validate-allele_test] Error 1
(venv) (base) christian_grove@ip-192-168-1-7 agr_curation_schema % make all
rm -rf target/*
rm -rf jsonschema/*
mkdir -p target/jsonschema
poetry run gen-json-schema  --closed -t ingest model/schema/allianceModel.yaml > target/jsonschema/allianceModel.schema.json
cp -pr target/jsonschema .
`
'make all' seems to run without issue

**Review by markquintontulloch — COMMENTED** [review]
We should probably remove the alliance_curie slot definition from core.yaml too in order to avoid confusion

**Comment by chris-grove** [comment]
@markquintontulloch 
OK, done (removed alliance_curie and fixed slot_usage)

**Review by markquintontulloch — APPROVED** [review]

**Pull request merged**
